// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Entfernen Sie die Unterstriche aus dem Assemblynamen \"IIS_LogfileProcessor_Fw472\".", Justification = "<Ausstehend>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Der Parameter \"newBans\" der Methode \"AddNewIpBansToIIS\" wird niemals verwendet. Entfernen Sie den Parameter, oder verwenden Sie ihn im Methodentext.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.AddNewIpBansToIIS(System.Collections.Generic.List{System.String})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Der Parameter \"bans\" der Methode \"DisplayAllBans\" wird niemals verwendet. Entfernen Sie den Parameter, oder verwenden Sie ihn im Methodentext.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.DisplayAllBans(System.Collections.Generic.List{Abraham.Web.Rule})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Das Verhalten von \"DateTime.ToString(string)\" kann je nach den Gebietsschemaeinstellungen des Benutzers variieren. Ersetzen Sie diesen Aufruf in \"Program.DisplayEntry(List<string>, Entry, string)\" durch einen Aufruf an \"DateTime.ToString(string, IFormatProvider)\".", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.DisplayEntry(System.Collections.Generic.List{System.String},Abraham.Web.Entry,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Die Methode \"void Program.DisplayFinalMessage()\" übergibt eine Literalzeichenfolge als Parameter \"value\" eines Aufrufs an \"void Console.WriteLine(string value)\". Rufen Sie die folgende(n) Zeichenfolge(n) stattdessen aus einer Ressourcentabelle ab: processing log entries finished.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.DisplayFinalMessage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Die Methode \"void Program.DisplayGreeting()\" übergibt eine Literalzeichenfolge als Parameter \"value\" eines Aufrufs an \"void Console.WriteLine(string value)\". Rufen Sie die folgende(n) Zeichenfolge(n) stattdessen aus einer Ressourcentabelle ab: IIS logfile processor - Oliver Abraham 2019 - mail@oliver-abraham.de.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.DisplayGreeting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Die Methode \"void Program.DisplayParameters()\" übergibt eine Literalzeichenfolge als Parameter \"value\" eines Aufrufs an \"void Console.WriteLine(string value)\". Rufen Sie die folgende(n) Zeichenfolge(n) stattdessen aus einer Ressourcentabelle ab: Blacklist:.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.DisplayParameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Die Methode \"void Program.DisplaySomeInformation()\" übergibt eine Literalzeichenfolge als Parameter \"value\" eines Aufrufs an \"void Console.WriteLine(string value)\". Rufen Sie die folgende(n) Zeichenfolge(n) stattdessen aus einer Ressourcentabelle ab: note: WhiteList calls are omitted..", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.DisplaySomeInformation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:Das Verhalten von \"string.StartsWith(string)\" kann je nach den Gebietsschemaeinstellungen des Benutzers variieren. Ersetzen Sie diesen Aufruf in \"IIS_LogfileProcessor_Fw472.Program.ItemIsOnList(string, System.Collections.Generic.List<string>)\" durch einen Aufruf an \"string.StartsWith(string, System.StringComparison)\".", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.ItemIsOnList(System.String,System.Collections.Generic.List{System.String})~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Der Parameter \"args\" der Methode \"Main\" wird niemals verwendet. Entfernen Sie den Parameter, oder verwenden Sie ihn im Methodentext.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Die Methode \"List<Entry> Program.ReadNewLogfileEntriesSinceLastRun()\" übergibt eine Literalzeichenfolge als Parameter \"value\" eines Aufrufs an \"void Console.WriteLine(string value)\". Rufen Sie die folgende(n) Zeichenfolge(n) stattdessen aus einer Ressourcentabelle ab: Errors reading the source directory:.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:IIS_LogfileProcessor_Fw472.Program.ReadNewLogfileEntriesSinceLastRun~System.Collections.Generic.List{Abraham.Web.Entry}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Entfernen Sie die Unterstriche aus dem Namespacenamen \"IIS_LogfileProcessor\".", Justification = "<Ausstehend>", Scope = "namespace", Target = "~N:IIS_LogfileProcessor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Entfernen Sie die Unterstriche aus dem Namespacenamen \"IIS_LogfileProcessor_Fw472\".", Justification = "<Ausstehend>", Scope = "namespace", Target = "~N:IIS_LogfileProcessor_Fw472")]